const greetings = [
    'Chúc bạn ngày 8/3 tràn đầy niềm vui và hạnh phúc! 🌸',
    'Gửi đến bạn ngàn lời yêu thương nhân ngày Quốc tế Phụ nữ! 💕',
    'Chúc bạn luôn xinh đẹp, tự tin và rạng ngời như ánh nắng ban mai! ☀️',
    'Bạn xứng đáng được yêu thương và trân trọng mỗi ngày, không chỉ riêng 8/3! 🌷',
    'Chúc người phụ nữ tuyệt vời luôn mạnh mẽ và dịu dàng! 💪🌹',
    'Mỗi ngày đều là ngày của bạn, nhưng hôm nay đặc biệt hơn cả! 🎀',
    'Cảm ơn vì đã làm cuộc sống này thêm tươi đẹp! 🌺',
    'Chúc bạn mãi giữ được nụ cười rạng rỡ ấy! 😊🌸',
    'Phụ nữ là những bông hoa đẹp nhất trong vườn đời! 🌻',
    'Hãy luôn yêu bản thân mình nhé, vì bạn thật sự rất đặc biệt! ✨',
    'Chúc ngày 8/3 của bạn ngập tràn hoa và yêu thương! 💐',
    'Bạn là nguồn cảm hứng cho tất cả mọi người xung quanh! 🌟',
    'Chúc bạn luôn hạnh phúc với mọi lựa chọn của mình! 🦋',
    'Ngày 8/3 này, hãy tận hưởng từng khoảnh khắc tuyệt vời nhé! 🥂',
    'Gửi bạn một vòng ôm thật ấm áp nhân ngày Phụ nữ! 🤗💖',
    'Chúc bạn ngày càng toả sáng và thành công hơn! ⭐',
    'Hãy cứ mơ mộng, vì bạn xứng đáng với mọi điều tốt đẹp nhất! 🌈',
    'Phụ nữ mạnh mẽ không phải vì không khóc, mà vì luôn đứng dậy sau mỗi lần vấp ngã! 💎',
    'Chúc bạn luôn được bao bọc bởi tình yêu thương! 🫶',
    'Ngày 8/3 an lành, hạnh phúc và thật nhiều niềm vui bạn nhé! 🎊',
    'Cảm ơn bạn vì luôn kiên cường và dịu dàng! 🌿',
    'Chúc tất cả những gì bạn mong ước đều trở thành hiện thực! 🙏✨',
    'Bạn đẹp nhất khi bạn là chính mình! 🪞🌸',
    'Hôm nay là ngày để bạn được chiều chuộng và yêu thương! 👑',
    'Chúc bạn có một ngày 8/3 đáng nhớ và ý nghĩa! 📸💗',
    'Gửi bạn những lời chúc ngọt ngào nhất! Yêu thương bạn! 🍬💝',
    'Hãy để ngày hôm nay là ngày bạn thật sự hạnh phúc! 🎉',
    'Bạn là ánh sáng, là niềm vui, là tất cả những gì đẹp đẽ! 🔆',
    'Chúc người phụ nữ của tôi luôn cười thật tươi! 😄🌼',
    'Ngày 8/3, gửi bạn cả bầu trời yêu thương! 💌☁️',
    'Mỗi bông hoa nở là một lời chúc dành riêng cho bạn! 🌺🌸🌷',
    'Chúc bạn luôn tìm thấy niềm vui trong những điều nhỏ bé nhất! 🍀',
    'Bạn mạnh mẽ hơn bạn nghĩ, đẹp hơn bạn thấy! 💫',
    'Hôm nay và mọi ngày, bạn đều xứng đáng được hạnh phúc! 🌅',
    'Chúc ngày 8/3 của bạn ấm áp như vòng tay yêu thương! 🫂',
    'Gửi đến bạn món quà là nụ cười và sự trân trọng! 🎁😊',
    'Phụ nữ là phép màu của cuộc sống! Chúc mừng ngày 8/3! ✨🌏',
    'Hãy sống thật trọn vẹn, vì bạn xứng đáng với điều đó! 🎈',
    'Chúc bạn luôn giữ được ngọn lửa đam mê trong tim! 🔥❤️',
    'Ngày Phụ nữ này, hãy nhớ rằng bạn thật phi thường! 🦸‍♀️',
    'Cảm ơn vì bạn luôn là nguồn động lực tuyệt vời! 💪🌟',
    'Chúc bạn ngày 8/3 thật lung linh như ánh sao! ⭐🌙',
    'Hãy yêu thương bản thân nhiều hơn nữa nhé! Bạn xứng đáng! 💖',
    'Chúc bạn mọi điều tốt lành và hạnh phúc viên mãn! 🎆🌷',
    'Bạn là người phụ nữ tuyệt vời nhất mà tôi từng biết! 👏💕',
    'Ngày 8/3, gửi bạn triệu đoá hồng và nghìn nụ hôn! 🌹💋',
    'Hãy luôn tự hào về con người tuyệt vời mà bạn đã trở thành! 🏆',
    'Chúc bạn ngập tràn hạnh phúc như biển hoa mùa xuân! 🌼🌼🌼',
    'Phụ nữ là thơ, là nhạc, là hoa — là tất cả điều đẹp đẽ! 🎵🌸',
    'Happy Women\'s Day! Chúc bạn luôn vui vẻ và bình an! 🕊️💗',
];

export default greetings;
